#include"stm32f10x.h"
void DAC_Init(){
	RCC->APB2ENR|=RCC_APB2ENR_IOPAEN;
	GPIOA->CRL&=~0x0FFFFFFF;
	GPIOA->CRL|=GPIO_CRL_MODE0|GPIO_CRL_MODE1|GPIO_CRL_MODE2|GPIO_CRL_MODE3|GPIO_CRL_MODE4|GPIO_CRL_MODE5;
}
void DAC_Out(uint32_t data){
	GPIOA->ODR=data;
}